name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Configure src/tables.rs cache
        id: cache-tables
        uses: actions/cache@v3
        with:
          path: src/tables.rs
          key: ${{ hashFiles('LineBreak.txt', 'gen-tables/**') }}

      - name: Generates src/tables.rs
        run: cargo run
        working-directory: ./gen-tables
        if: steps.cache-tables.outputs.cache-hit != 'true'

      - name: Run tests
        run: cargo test
